project_name: trivy_output_plugin_kafka
builds:
  -
    main: .
    binary: kafka
    ldflags:
      - -s -w
      - "-extldflags '-static'"
      - -X main.version={{.Version}}
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64

archives:
  -
    format: tar.gz
    name_template: "{{.ProjectName}}_{{.Os}}-{{.Arch}}"
    files:
      - README.md
      - LICENSE
      - plugin.yaml