name: "kafka"
version: "1.0.1"
repository: "https://github.com/phankhanhpvk/trivy-plugin-output-to-kafka"
usage: Put log json to kafka
description: Put log json to kafka
platforms:
  - selector:
      os: linux
      arch: amd64
    bin: ./kafka
    uri: https://github.com/phankhanhpvk/trivy-plugin-output-to-kafka/releases/download/v1.0.0/trivy_output_plugin_kafka_1.0.1_linux-amd64.tar.gz
  - selector:
      os: linux
      arch: arm64
    bin: ./kafka
    uri: https://github.com/phankhanhpvk/trivy-plugin-output-to-kafka/releases/download/v1.0.0/trivy_output_plugin_kafka_1.0.1_linux-arm64.tar.gz
  - selector:
      os: darwin
      arch: amd64
    bin: ./kafka
    uri: https://github.com/phankhanhpvk/trivy-plugin-output-to-kafka/releases/download/v1.0.0/trivy_output_plugin_kafka_1.0.1_darwin-amd64.tar.gz
  - selector:
      os: darwin
      arch: arm64
    bin: ./kafka
    uri: https://github.com/phankhanhpvk/trivy-plugin-output-to-kafka/releases/download/v1.0.0/trivy_output_plugin_kafka_1.0.1_darwin-arm64.tar.gz
