name: "kafka"
version: "v1.0.1"
repository: "https://github.com/phankhanhpvk/trivy-plugin-output-to-kafka"
usage: Put log json to kafka
description: Put log json to kafka
platforms:
  - selector:
      os: linux
      arch: amd64
    bin: ./kafka
    uri: https://github.com/phankhanhpvk/trivy-plugin-output-to-kafka/releases/download/{{.Version}}/{{.ProjectName}}_{{.Os}}-{{.Arch}}.tar.gz
  - selector:
      os: linux
      arch: arm64
    bin: ./kafka
    uri: https://github.com/phankhanhpvk/trivy-plugin-output-to-kafka/releases/download/{{.Version}}/{{.ProjectName}}_{{.Os}}-{{.Arch}}.tar.gz
  - selector:
      os: darwin
      arch: amd64
    bin: ./kafka
    uri: https://github.com/phankhanhpvk/trivy-plugin-output-to-kafka/releases/download/{{.Version}}/{{.ProjectName}}_{{.Os}}-{{.Arch}}.tar.gz
  - selector:
      os: darwin
      arch: arm64
    bin: ./kafka
    uri: https://github.com/phankhanhpvk/trivy-plugin-output-to-kafka/releases/download/{{.Version}}/{{.ProjectName}}_{{.Os}}-{{.Arch}}.tar.gz
