name: "kafka"
version: "1.0.0"
repository: "https://github.com/phankhanhpvk/trivy-plugin-output-to-kafka"
usage: Put log json to kafka
description: Put log json to kafka
platforms:
  - selector:
      os: linux
      arch: amd64
    bin: ./kafka
    uri: https://github.com/phankhanhpvk/trivy-plugin-output-to-kafka/-/releases/v0.1.0/downloads/trivy_output_plugin_kafka_0.1.0_linux-amd64.tar.gz
  - selector:
      os: linux
      arch: arm64
    bin: ./kafka
    uri: https://github.com/phankhanhpvk/trivy-plugin-output-to-kafka/-/releases/v0.1.0/downloads/trivy_output_plugin_kafka_0.1.0_linux-arm64.tar.gz
    
